name:                flickr-promoter
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/dzhus/flickr-promoter#readme
license:             BSD3
author:              Dmitry Dzhus
maintainer:          dima@dzhus.org
copyright:           Dmitry Dzhus 2020
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - authenticate-oauth
  - base64-bytestring
  - binary
  - bytestring
  - classy-prelude
  - containers
  - http-client
  - http-client-tls
  - http-media
  - http-types
  - microlens
  - modern-uri
  - polysemy
  - random
  - servant
  - servant-client
  - servant-client-core
  - SHA
  - text
  - time
  - turtle

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  flickr-promoter:
    source-dirs:      src
    main:             Main.hs
