name: Build & test
on:
  push:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack_yaml: ['stack.yaml']
    steps:
      - name: Setup Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Clone project
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ matrix.stack_yaml }}-${{ hashFiles(matrix.stack_yaml) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.stack_yaml }}-
            ${{ runner.os }}-

      - name: 'Set up HLint'
        uses: haskell-actions/hlint-setup@v2

      - name: 'Run HLint'
        uses: haskell-actions/hlint-run@v2
        with:
          path: src/
          fail-on: warning

      - name: Build and run tests
        run: 'stack build --fast --no-terminal --stack-yaml=${{ matrix.stack_yaml }} --pedantic --haddock --no-haddock-deps --test --bench --no-run-benchmarks'
