name: Daily run
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Clone project
        uses: actions/checkout@v3

      - name: Build
        run:
          stack build --fast

      - name: Run
        run: >-
          FLICKR_PROMOTER_ACCESS_TOKEN=${{secrets.FLICKR_PROMOTER_ACCESS_TOKEN}}
          FLICKR_PROMOTER_API_KEY=${{secrets.FLICKR_PROMOTER_API_KEY}}
          FLICKR_PROMOTER_API_SECRET=${{secrets.FLICKR_PROMOTER_API_SECRET}}
          stack exec -- flickr-promoter
