name: Daily run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: pip install .

      - name: Run
        env:
          FLICKR_PROMOTER_API_KEY: ${{ secrets.FLICKR_PROMOTER_API_KEY }}
          FLICKR_PROMOTER_API_SECRET: ${{ secrets.FLICKR_PROMOTER_API_SECRET }}
          FLICKR_PROMOTER_OAUTH_TOKEN: ${{ secrets.FLICKR_PROMOTER_OAUTH_TOKEN }}
          FLICKR_PROMOTER_OAUTH_TOKEN_SECRET: ${{ secrets.FLICKR_PROMOTER_OAUTH_TOKEN_SECRET }}
        run: flickr-promoter
