name: Build & test
on:
  schedule:
    - cron: '45 11 * * *'

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup Stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.stack_yaml }}-${{ hashFiles(matrix.stack_yaml) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.stack_yaml }}-
            ${{ runner.os }}-
      - name: Run
        run: >-
          FLICKR_PROMOTER_ACCESS_TOKEN=${{secrets.FLICKR_PROMOTER_ACCESS_TOKEN}}
          FLICKR_PROMOTER_API_KEY=${{secrets.FLICKR_PROMOTER_API_KEY}}
          FLICKR_PROMOTER_API_SECRET=${{secrets.FLICKR_PROMOTER_API_SECRET}}
          stack exec -- flickr-promoter
